version: '3.8'

services:
  app:
    image: node:14
    container_name: soccer-meetup-tracker
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"
    environment:
      NODE_ENV: development
